services: 
  web:
    image: boulundeasv/dora-meter
    ports:
      - "8080:8080"
    
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: web --debug --http-api-update
    ports:
      - "8888:8080"
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_HTTP_API_TOKEN=TEMPTOKEN # TODO: Skift denne