services: 
  api:
    image: ghcr.io/tboulund-devops/dora-meter-api
    ports:
      - "8080:8080"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker/config.json:/config.json # Share the Docker config file with WatchTower for authentication
    command: --debug --http-api-update
    ports:
      - "8888:8080"
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_HTTP_API_TOKEN=TEMPTOKEN # TODO: Skift denne
  
  maria-db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: lbw|Z_9?15=48>Z8
      MYSQL_DATABASE: dora_meter
      MYSQL_USER: dbadmin
      MYSQL_PASSWORD: TogetherCenterExceptThusFew
    ports:
      - "3306:3306"