name: DevOpsPipeline

on:
  push:
    branches:
      - main
    
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Start test database
        run: docker compose -f tests/docker-compose.yml up -d
        
      - name: Run tests
        run: dotnet test tests/unit/UnitTests/UnitTests.csproj
        
  delivery:
    needs: integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }} # The user who initiated the workflow
          password: ${{ secrets.GITHUB_TOKEN }} # Automatically assigned by GitHub Actions

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/tboulund-devops/dora-meter-api -f src/API/Dockerfile .
          docker push ghcr.io/tboulund-devops/dora-meter-api
          
  deployment:
    runs-on: ubuntu-latest
    needs: delivery
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Update through WatchTower
        run: | # Notice the $ in front of the variable - it's neccessary because we're in a string
          curl -H "Authorization: Bearer TEMPTOKEN" http://${{ vars.SERVER_IP }}:8888/v1/update
      
      - name: Update databases with Flyway
        run: |
          docker run --rm \
            -v ${{ GITHUB.WORKSPACE }}/db:/flyway/sql \
            -e FLYWAY_URL=jdbc:mariadb://${{ vars.SERVER_IP }}:3306/dora_meter \
            -e FLYWAY_USER=dbadmin \
            -e FLYWAY_PASSWORD=TogetherCenterExceptThusFew \
            flyway/flyway migrate