name: TeamWorkflow

on:
  push:
    branches:
      - main
    
jobs:
  integration:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: src/DORAMeter/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/dora-meter:latest
          
      - name: Update through WatchTower
        run: |
          curl -H "Authorization: Bearer TEMPTOKEN" {{ vars.SERVER_IP }}:8080/v1/update
          